name: Build and push Docker image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/Media-Magic/Magic-Media-Discord-Bot:latest
          cache-to: type=inline
          tags: |
            ghcr.io/Media-Magic/Magic-Media-Discord-Bot:latest
            ghcr.io/Media-Magic/Magic-Media-Discord-Bot:${{ github.sha }}
