name: Bot Runner

on:
  workflow_dispatch:

permissions:
  read-all

jobs:
  run:
    runs-on: ubuntu-latest

  permissions:
    contents: read

    steps:
    - name: Run Container
      run: |
        docker run -i  -e TOKEN=${{ secrets.token }} ghcr.io/media-magic/magic-media-discord-bot:latest
